name: anu

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run-gh-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run gh API command
        run: gh api https://api.github.com/user
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
